#!/bin/bash
#SBATCH -J C4459           # job name
#SBATCH -o C4459.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 24              # total number of mpi tasks requested, i use 24 but you can try changing it
#SBATCH -p normal     # queue (partition) -- normal, development, etc.
#SBATCH -t 48:00:00        # run time (hh:mm:ss) - 1.5 hours, this takes ~30h
#SBATCH --mail-user=brandoncarr09@gmail.com
#SBATCH --mail-type=begin
#SBATCH --mail-type=end    # email me when the job finishes

python Calcraps.py 10605_UGC-04459  		#change to fit correct script name
